matrix:
  include:
  - language: java
    script:
    - "./gradlew build"
    deploy:
      provider: heroku
      api_key:
        secure: iKB6bPYFw6OQLOSJMMRoZQ/o14En1njrcRiNLIHVPB+QS6CEszanboXnaEPi9qfFHoz53pkExwr6KYQYmqlSzYvGNxn8u1cMizflT6OGcIQ2Cc8e7AKmPH3zdcd0q0fp9Ij6d5qLrsazkqvenm16fiwlryE2SW71mdGS/fYqZDMpAemd9JqlSqEcRuGYVEFQf96/jl6337ZqCiSU+dmYwXDrrfT/5zP2N6gkJq9THxDfFFLL2m5pDtW/YCBzNGvlK/wRZR7KhNcI2CGVyKMOlL3fRVRXxxRlMJZYs3UIBxsfQkrTfubhJdNihN91AUT+f6pexb7KsG7gkU8BOSQqsaMxYtAdocgdvULn2um2ITUFEFLh3Mo/Tjpq6mRQCH/wdh5zT5OzclOVjGRvhZlVQXfrW8KK6DZtL16NaaAYUrRBO11KE0YWrJAAxGxC8E/BImy4RRFQwXPJXv102nVm0a2Mfa3qnNuZxc0+p+Kkf8NbrjUI3oov9TmIk8uLVJsF3XUb058hDePc9QA0i2bwWT03o4n2rr3vyIBHG+/JDmU7poaVBDNqMIqroGTJfKt86omgvKnH2mDnFLNGJBSlUGWQqXHSgstm1G07Ch7+/Ohd2fi/f0Je9lUePt+CQ4uuT93M8N6OlxjBBSIiui7/rBXKqf9qoU9qW/Ux2fRLdTQ=
      app: cooperator-backend-21

  - language: node_js
    node_js:
    - node
    before_install:
    - cd Frontend
    - npm i -g npm@6.9.0
    install:
    - npm install
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: iKB6bPYFw6OQLOSJMMRoZQ/o14En1njrcRiNLIHVPB+QS6CEszanboXnaEPi9qfFHoz53pkExwr6KYQYmqlSzYvGNxn8u1cMizflT6OGcIQ2Cc8e7AKmPH3zdcd0q0fp9Ij6d5qLrsazkqvenm16fiwlryE2SW71mdGS/fYqZDMpAemd9JqlSqEcRuGYVEFQf96/jl6337ZqCiSU+dmYwXDrrfT/5zP2N6gkJq9THxDfFFLL2m5pDtW/YCBzNGvlK/wRZR7KhNcI2CGVyKMOlL3fRVRXxxRlMJZYs3UIBxsfQkrTfubhJdNihN91AUT+f6pexb7KsG7gkU8BOSQqsaMxYtAdocgdvULn2um2ITUFEFLh3Mo/Tjpq6mRQCH/wdh5zT5OzclOVjGRvhZlVQXfrW8KK6DZtL16NaaAYUrRBO11KE0YWrJAAxGxC8E/BImy4RRFQwXPJXv102nVm0a2Mfa3qnNuZxc0+p+Kkf8NbrjUI3oov9TmIk8uLVJsF3XUb058hDePc9QA0i2bwWT03o4n2rr3vyIBHG+/JDmU7poaVBDNqMIqroGTJfKt86omgvKnH2mDnFLNGJBSlUGWQqXHSgstm1G07Ch7+/Ohd2fi/f0Je9lUePt+CQ4uuT93M8N6OlxjBBSIiui7/rBXKqf9qoU9qW/Ux2fRLdTQ=
      app: cooperator-frontend-21

  