matrix:
  include:
  - language: java
    script:
    - "./gradlew build"
    deploy:
      provider: heroku
      api_key:
        secure: aw5I/YeqZEMdnFIUjhfjoj5+yOymCMRUbzTrAMQDVnCY1taW98iFDFdgRRkpyzAHmloz4fd7WZKZ93llmNzZPIMT+HLL87gIwQBcgo1DtwP2qYRZaDInKL7eAMcsPL9uvnIWaEF1MCHM3cu2hpmdaMY+V1hzGU2MYYeFV4PNevwrtZ/L9cSW35wQFTYiW8whpMZvAipncA4BYJEC/ZlFm8MGSmFb7L43tsqgRvuQagqDgoWE1zn+X656ErX4b+Nz1pvf26qpLqWhUqtWSVJulSW6IxF2eMUkVpR6bYEJCvaKBk3VyXwPHKCtSF3ZXL2PMxgsZQ18YCo2sD1KvePTycPVLyi12ms5fuKQth27iBwj1EkTfo+Zd/LgsFBhsQE8sadHas10o8iY/ciVqKwL3Ghc2DYH8GrugtobmlNVbDqUCxcD/9GclWdgM/lvMKlJznSLT5iLDoYG4c1D71QJBF4L4Ic8IAKtm4QZBIWbx5tmJeIhJ4xPwB9fv0Y/jtIHgY4/f4QKlTgmZ2yXUG83mUeicxGQaK2Lu9ZST2IzDfZd3yJpwBuHnSQaw74jTDJ5kRTB+mIQ/ARWPCsTK3sEUlErs6hPeijpMDGGWEP7WIq7SeejUmxAbpaaXUzStSZuboYo9VvnbhyJxFIiAK2pxelV5d/I5MneWTNDQgsv334=
      app: cooperator-backend-21
  - language: node_js
    node_js:
    - node
    before_install:
    - cd Frontend
    install:
    - npm install
    script:
    - npm run build
    deploy:
      provider: heroku
      api_key:
        secure: aw5I/YeqZEMdnFIUjhfjoj5+yOymCMRUbzTrAMQDVnCY1taW98iFDFdgRRkpyzAHmloz4fd7WZKZ93llmNzZPIMT+HLL87gIwQBcgo1DtwP2qYRZaDInKL7eAMcsPL9uvnIWaEF1MCHM3cu2hpmdaMY+V1hzGU2MYYeFV4PNevwrtZ/L9cSW35wQFTYiW8whpMZvAipncA4BYJEC/ZlFm8MGSmFb7L43tsqgRvuQagqDgoWE1zn+X656ErX4b+Nz1pvf26qpLqWhUqtWSVJulSW6IxF2eMUkVpR6bYEJCvaKBk3VyXwPHKCtSF3ZXL2PMxgsZQ18YCo2sD1KvePTycPVLyi12ms5fuKQth27iBwj1EkTfo+Zd/LgsFBhsQE8sadHas10o8iY/ciVqKwL3Ghc2DYH8GrugtobmlNVbDqUCxcD/9GclWdgM/lvMKlJznSLT5iLDoYG4c1D71QJBF4L4Ic8IAKtm4QZBIWbx5tmJeIhJ4xPwB9fv0Y/jtIHgY4/f4QKlTgmZ2yXUG83mUeicxGQaK2Lu9ZST2IzDfZd3yJpwBuHnSQaw74jTDJ5kRTB+mIQ/ARWPCsTK3sEUlErs6hPeijpMDGGWEP7WIq7SeejUmxAbpaaXUzStSZuboYo9VvnbhyJxFIiAK2pxelV5d/I5MneWTNDQgsv334=
      app: cooperator-frontend-21