language: java
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: HlypjGYitfhp5LIr16NFJVo1mjW2d0nZASFCUOcSGYIk55ddsw7tvfazIO4CJHpls9HMUpkGXScIJWxiJMUrlKXxxHHi7A1+RCcIdSpk0uAg1RIySceCvbiRmvj4tQDQddz7THo7DRK9/v5QOBverryeuVRA/ZZAtkSJTYzJ19ha8DiAE3SJn+L8r5wHHLqKxksNowxIEWkTVBHq+ATr+mC7vwYYtHNTXEUdTDkA2MfTOoauFW3++cgpP+Dpj8x+6z0Tfs0EZo0DldbjBH3A7HCzXdKo4ssaGD/ESmrv9oKxFgvM44YMgfY5rQKxGO8+olEt5LPRu36FHvgTCatR6kt9e/GDduUgsvrHPQVzhIcQYrjUGSDnYI9HU/33dcgWPvp0bZu96aDCpMKKr3aN4BwkcUk7Er89raxScrzoVy8V1oDnb6bZCr8SrgNHcWfI99tDMlZv1YiYYtbg2svx8WeWjbfvAspovkJ4PfBZRFx0aUxt4j9KAu0JXP6et1MAJy8Pkl5qk6jJs82kt0fSUtGQrpBUzKXAmqnla6TKIcPOk0N6wUJz2TAejn8dxsFm7Y6WDpee+CaCMF2ZHjtFlhI0HLedn3Hq4J3ZWVuop4N4gHrpNvz8QNjjwZtRFWGXXjHbKUAGKcfbV/xiyGNiJrnWrLLQgQr21XR9ZW9FPEM=
  app: cooperator-backend-21
  on: Alex

